export const THEMES = {
  paises: [
    "Afeganistão",
    "África do Sul",
    "Alemanha",
    "Andorra",
    "Angola",
    "Antígua e Barbuda",
    "Arábia Saudita",
    "Argélia",
    "Argentina",
    "Armênia",
    "Austrália",
    "Áustria",
    "Azerbaijão",
    "Bahamas",
    "Bangladesh",
    "Barbados",
    "Bélgica",
    "Belize",
    "Benin",
    "Bielorrússia",
    "Bolívia",
    "Bósnia e Herzegovina",
    "Botsuana",
    "Brasil",
    "Brunei",
    "Bulgária",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Camarões",
    "Camboja",
    "Canadá",
    "Catar",
    "Cazaquistão",
    "Chade",
    "Chile",
    "China",
    "Chipre",
    "Colômbia",
    "Comores",
    "Coreia do Norte",
    "Coreia do Sul",
    "Costa do Marfim",
    "Costa Rica",
    "Croácia",
    "Cuba",
    "Dinamarca",
    "Djibuti",
    "Dominica",
    "Egito",
    "El Salvador",
    "Emirados Árabes Unidos",
    "Equador",
    "Eritreia",
    "Eslováquia",
    "Eslovênia",
    "Espanha",
    "Estados Unidos",
    "Estônia",
    "Etiópia",
    "Fiji",
    "Filipinas",
    "Finlândia",
    "França",
    "Gabão",
    "Gâmbia",
    "Gana",
    "Geórgia",
    "Grécia",
    "Granada",
    "Guatemala",
    "Guiana",
    "Guiné",
    "Guiné-Bissau",
    "Guiné Equatorial",
    "Haiti",
    "Honduras",
    "Hungria",
    "Iêmen",
    "Índia",
    "Indonésia",
    "Irã",
    "Iraque",
    "Irlanda",
    "Islândia",
    "Israel",
    "Itália",
    "Jamaica",
    "Japão",
    "Jordânia",
    "Kiribati",
    "Kuwait",
    "Laos",
    "Lesoto",
    "Letônia",
    "Líbano",
    "Libéria",
    "Líbia",
    "Liechtenstein",
    "Lituânia",
    "Luxemburgo",
    "Macedônia do Norte",
    "Madagascar",
    "Malásia",
    "Malaui",
    "Maldivas",
    "Mali",
    "Malta",
    "Marrocos",
    "Ilhas Marshall",
    "Maurícia",
    "Mauritânia",
    "México",
    "Micronésia",
    "Moçambique",
    "Moldávia",
    "Mônaco",
    "Mongólia",
    "Montenegro",
    "Mianmar",
    "Namíbia",
    "Nauru",
    "Nepal",
    "Nicarágua",
    "Níger",
    "Nigéria",
    "Noruega",
    "Nova Zelândia",
    "Omã",
    "Países Baixos",
    "Palau",
    "Panamá",
    "Papua-Nova Guiné",
    "Paquistão",
    "Paraguai",
    "Peru",
    "Polônia",
    "Portugal",
    "Quênia",
    "Quirguistão",
    "Reino Unido",
    "República Centro-Africana",
    "República Checa",
    "República Democrática do Congo",
    "República do Congo",
    "República Dominicana",
    "Romênia",
    "Ruanda",
    "Rússia",
    "Salomão",
    "El Salvador",
    "Samoa",
    "San Marino",
    "Santa Lúcia",
    "São Cristóvão e Neves",
    "São Tomé e Príncipe",
    "São Vicente e Granadinas",
    "Seicheles",
    "Senegal",
    "Serra Leoa",
    "Sérvia",
    "Singapura",
    "Síria",
    "Somália",
    "Sri Lanka",
    "Suazilândia",
    "Sudão",
    "Sudão do Sul",
    "Suécia",
    "Suíça",
    "Suriname",
    "Tailândia",
    "Tajiquistão",
    "Tanzânia",
    "Togo",
    "Tonga",
    "Trindade e Tobago",
    "Tunísia",
    "Turcomenistão",
    "Turquia",
    "Tuvalu",
    "Ucrânia",
    "Uganda",
    "Uruguai",
    "Uzbequistão",
    "Vanuatu",
    "Vaticano",
    "Venezuela",
    "Vietnã",
    "Zâmbia",
    "Zimbábue",
  ],
  animais: [
    "Abelha",
    "Águia",
    "Albatroz",
    "Alce",
    "Anaconda",
    "Andorinha",
    "Antílope",
    "Aranha",
    "Arara",
    "Ariranha",
    "Arraia",
    "Atum",
    "Avestruz",
    "Axolote",
    "Babuíno",
    "Baleia",
    "Barata",
    "Barbo",
    "Beija-flor",
    "Bem-te-vi",
    "Besouro",
    "Bode",
    "Boi",
    "Borboleta",
    "Cabra",
    "Cachalote",
    "Cachorro",
    "Cágado",
    "Camaleão",
    "Camelo",
    "Canguru",
    "Capivara",
    "Caracol",
    "Caranguejo",
    "Carneiro",
    "Cascavel",
    "Castor",
    "Cavalo",
    "Cavalo-marinho",
    "Cegonha",
    "Chacal",
    "Chimpanzé",
    "Cigarra",
    "Coala",
    "Cobra",
    "Coelho",
    "Condor",
    "Coruja",
    "Corvo",
    "Crocodilo",
    "Cupim",
    "Diabo-da-Tasmânia",
    "Dinossauro",
    "Doninha",
    "Dragão-de-Komodo",
    "Elefante",
    "Ema",
    "Enguia",
    "Escorpião",
    "Esquilo",
    "Estrela-do-mar",
    "Faisão",
    "Falcão",
    "Flamingo",
    "Foca",
    "Formiga",
    "Furão",
    "Gafanhoto",
    "Galinha",
    "Galo",
    "Garça",
    "Gato",
    "Gavião",
    "Geco",
    "Girafa",
    "Gnu",
    "Golfinho",
    "Gorila",
    "Grilo",
    "Guepardo",
    "Hamster",
    "Hiena",
    "Hipopótamo",
    "Iguana",
    "Irara",
    "Jabuti",
    "Jacaré",
    "Jaguar",
    "Javali",
    "Joaninha",
    "João-de-barro",
    "Lagarta",
    "Lagarto",
    "Lagosta",
    "Leão",
    "Leão-marinho",
    "Lebre",
    "Lêmure",
    "Leopardo",
    "Lhama",
    "Libélula",
    "Lince",
    "Lobo",
    "Lontra",
    "Louva-a-deus",
    "Lula",
    "Macaco",
    "Mariposa",
    "Medusa",
    "Mico-leão-dourado",
    "Minhoca",
    "Morcego",
    "Moreia",
    "Morsa",
    "Mosca",
    "Mosquito",
    "Musaranho",
    "Narval",
    "Naja",
    "Ocapi",
    "Onça-pintada",
    "Orangotango",
    "Ornitorrinco",
    "Ostra",
    "Ovelha",
    "Panda",
    "Pantera",
    "Papagaio",
    "Pato",
    "Pavão",
    "Peixe",
    "Peixe-boi",
    "Pelicano",
    "Perereca",
    "Pinguim",
    "Piranha",
    "Polvo",
    "Pombo",
    "Pônei",
    "Porco",
    "Porco-espinho",
    "Preguiça",
    "Pulga",
    "Puma",
    "Quati",
    "Quero-quero",
    "Raposa",
    "Rato",
    "Rena",
    "Rinoceronte",
    "Rouxinol",
    "Salamandra",
    "Salmão",
    "Sapo",
    "Suricato",
    "Tamanduá",
    "Tartaruga",
    "Tatu",
    "Texugo",
    "Tigre",
    "Toupeira",
    "Touro",
    "Tritão",
    "Tubarão",
    "Tucano",
    "Urso",
    "Urubu",
    "Vaca",
    "Vaga-lume",
    "Veado",
    "Vespa",
    "Zebra",
    "Zebu",
  ],
  comidas: [
    "Abacate",
    "Abacaxi",
    "Açaí",
    "Acelga",
    "Alface",
    "Alho",
    "Amendoim",
    "Arroz",
    "Aveia",
    "Azeite",
    "Azeitona",
    "Bacon",
    "Banana",
    "Batata",
    "Berinjela",
    "Beterraba",
    "Biscoito",
    "Bolo",
    "Brócolis",
    "Cacau",
    "Café",
    "Caju",
    "Caldo",
    "Camarão",
    "Carne",
    "Cebola",
    "Cenoura",
    "Cereal",
    "Cereja",
    "Cerveja",
    "Chá",
    "Chocolate",
    "Churrasco",
    "Coco",
    "Couve",
    "Coxinha",
    "Empada",
    "Ervilha",
    "Espaguete",
    "Espinafre",
    "Farinha",
    "Feijão",
    "Figo",
    "Frango",
    "Goiaba",
    "Hambúrguer",
    "Iogurte",
    "Jaca",
    "Laranja",
    "Lasanha",
    "Leite",
    "Lentilha",
    "Limão",
    "Linguíça",
    "Maçã",
    "Macarrão",
    "Mamão",
    "Mandioca",
    "Manteiga",
    "Maracujá",
    "Mel",
    "Melancia",
    "Melão",
    "Milho",
    "Morango",
    "Mostarda",
    "Nozes",
    "Omelete",
    "Ovo",
    "Pão",
    "Pastel",
    "Pato",
    "Peixe",
    "Pepino",
    "Pera",
    "Pimenta",
    "Pimentão",
    "Pipoca",
    "Pizza",
    "Polenta",
    "Porco",
    "Pudim",
    "Queijo",
    "Quiabo",
    "Repolho",
    "Risoto",
    "Salsicha",
    "Sanduíche",
    "Sopa",
    "Sorvete",
    "Suco",
    "Sushi",
    "Tapioca",
    "Tomate",
    "Torrada",
    "Trigo",
    "Waffle",
    "Yakisoba",
    "Açúcar",
    "Alcatra",
    "Almôndega",
    "Amora",
    "Anchova",
    "Anis",
    "Aspargo",
    "Atum",
    "Baba de Moça",
    "Bacalhau",
    "Bagete",
    "Baião de Dois",
    "Baklava",
    "Banquete",
    "Barreado",
    "Batata Doce",
    "Baunilha",
    "Beijinho",
    "Beirute",
    "Bife",
    "Bisnaguinha",
    "Bobó de Camarão",
    "Bolinho de Chuva",
    "Brigadeiro",
    "Brioche",
    "Brownie",
    "Burrito",
    "Cafta",
    "Calabresa",
    "Canelone",
    "Canja",
    "Canjica",
    "Cappelletti",
    "Cappuccino",
    "Carambola",
    "Carbonara",
    "Carne Seca",
    "Carpaccio",
    "Casquinha de Siri",
    "Castanha",
    "Caviar",
    "Ceviche",
    "Chambaril",
    "Champignon",
    "Chantilly",
    "Charque",
    "Cheesecake",
    "Chimichurri",
    "Chocotone",
    "Chouriço",
    "Churros",
    "Coalhada",
    "Codorna",
    "Cogumelo",
    "Confeiteiro",
    "Conhaque",
    "Cookies",
    "Costela",
    "Couscous",
    "Crepioca",
    "Crepe",
    "Croissant",
    "Croquete",
    "Cuca",
    "Cuscuz",
    "Damasco",
    "Dobradinha",
    "Donut",
    "Doce de Leite",
    "Doritos",
    "Esfiha",
    "Espetinho",
    "Estrogonofe",
    "Extrato de Tomate",
    "Farofa",
    "Feijoada",
    "Fermento",
    "Filé Mignon",
    "Flan",
    "Focaccia",
    "Fondue",
    "Framboesa",
    "Fricassê",
    "Fritura",
    "Frutos do Mar",
    "Fubá",
    "Galinhada",
    "Gelatina",
    "Geleia",
    "Gergelim",
    "Gnocchi",
    "Gorgonzola",
    "Granola",
    "Grão de Bico",
    "Guacamole",
    "Guaraná",
    "Guariroba",
    "Haddock",
    "Hóstia",
    "Hummus",
  ],
  filmes: [
    "O Poderoso Chefão",
    "Pulp Fiction",
    "O Senhor dos Anéis",
    "Clube da Luta",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Cidade de Deus",
    "O Rei Leão",
    "Gladiador",
    "Titanic",
    "Jurassic Park",
    "Star Wars",
    "Vingadores",
    "O Cavaleiro das Trevas",
    "Avatar",
    "Harry Potter",
    "Coringa",
    "Parasita",
    "Interestelar",
    "De Volta para o Futuro",
    "Indiana Jones",
    "Toy Story",
    "Shrek",
    "Bastardos Inglórios",
    "O Resgate do Soldado Ryan",
    "Beleza Americana",
    "Psicose",
    "Laranja Mecânica",
    "O Iluminado",
    "O Silêncio dos Inocentes",
    "Coração Valente",
    "Blade Runner",
    "Alien",
    "Exterminador do Futuro",
    "Scarface",
    "Tubarão",
    "E.T. O Extraterrestre",
    "O Show de Truman",
    "Sociedade dos Poetas Mortos",
    "Rambo",
    "Rocky",
    "Mad Max",
    "Kill Bill",
    "Up Altas Aventuras",
    "Procurando Nemo",
    "Divertida Mente",
    "Frozen",
    "Moana",
    "Coco Viva a Vida é uma Festa",
    "Ratatouille",
    "Wall-E",
    "Carros",
    "Os Incríveis",
    "Monstros S.A.",
    "O Labirinto do Fauno",
    "Amélie Poulain",
    "Central do Brasil",
    "Tropa de Elite",
    "O Auto da Compadecida",
    "Bacurau",
    "Minha Mãe é uma Peça",
    "Dona Flor e Seus Dois Maridos",
    "Lisbela e o Prisioneiro",
    "O Palhaço",
    "Bingo O Rei das Manhãs",
    "Como Treinar o Seu Dragão",
    "Kung Fu Panda",
    "Madagascar",
    "A Era do Gelo",
  ],
  profissoes: [
    "Advogado",
    "Arquiteto",
    "Astronauta",
    "Ator",
    "Bombeiro",
    "Chef",
    "Cientista",
    "Contador",
    "Dentista",
    "Designer",
    "Diplomata",
    "Economista",
    "Editor",
    "Eletricista",
    "Encanador",
    "Enfermeiro",
    "Engenheiro",
    "Escritor",
    "Farmacêutico",
    "Fotógrafo",
    "Fisioterapeuta",
    "Geólogo",
    "Gerente",
    "Historiador",
    "Jornalista",
    "Juiz",
    "Lixeiro",
    "Marinheiro",
    "Mecânico",
    "Médico",
    "Músico",
    "Nutricionista",
    "Oceanógrafo",
    "Padeiro",
    "Paleontólogo",
    "Palhaço",
    "Pescador",
    "Piloto",
    "Pintor",
    "Policial",
    "Político",
    "Professor",
    "Programador",
    "Psicólogo",
    "Publicitário",
    "Químico",
    "Radialista",
    "Recepcionista",
    "Repórter",
    "Secretário",
    "Sociólogo",
    "Soldado",
    "Taxista",
    "Tradutor",
    "Treinador",
    "Turismólogo",
    "Vendedor",
    "Veterinário",
    "Web Designer",
    "Zootecnista",
  ],
  pokemons: [
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "Nidoran♀",
    "Nidorina",
    "Nidoqueen",
    "Nidoran♂",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch'd",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Sentret",
    "Furret",
    "Hoothoot",
    "Noctowl",
    "Ledyba",
    "Ledian",
    "Spinarak",
    "Ariados",
    "Crobat",
    "Chinchou",
    "Lanturn",
    "Pichu",
    "Cleffa",
    "Igglybuff",
    "Togepi",
    "Togetic",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Bellossom",
    "Marill",
    "Azumarill",
    "Sudowoodo",
    "Politoed",
    "Hoppip",
    "Skiploom",
    "Jumpluff",
    "Aipom",
    "Sunkern",
    "Sunflora",
    "Yanma",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Murkrow",
    "Slowking",
    "Misdreavus",
    "Unown",
    "Wobbuffet",
    "Girafarig",
    "Pineco",
    "Forretress",
    "Dunsparce",
    "Gligar",
    "Steelix",
    "Snubbull",
    "Granbull",
    "Qwilfish",
    "Scizor",
    "Shuckle",
    "Heracross",
    "Sneasel",
    "Teddiursa",
    "Ursaring",
    "Slugma",
    "Magcargo",
    "Swinub",
    "Piloswine",
    "Corsola",
    "Remoraid",
    "Octillery",
    "Delibird",
    "Mantine",
    "Skarmory",
    "Houndour",
    "Houndoom",
    "Kingdra",
    "Phanpy",
    "Donphan",
    "Porygon2",
    "Stantler",
    "Smeargle",
    "Tyrogue",
    "Hitmontop",
    "Smoochum",
    "Elekid",
    "Magby",
    "Miltank",
    "Blissey",
    "Raikou",
    "Entei",
    "Suicune",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Lugia",
    "Ho-Oh",
    "Celebi",
    "Treecko",
    "Grovyle",
    "Sceptile",
    "Torchic",
    "Combusken",
    "Blaziken",
    "Mudkip",
    "Marshtomp",
    "Swampert",
    "Poochyena",
    "Mightyena",
    "Zigzagoon",
    "Linoone",
    "Wurmple",
    "Silcoon",
    "Beautifly",
    "Cascoon",
    "Dustox",
    "Lotad",
    "Lombre",
    "Ludicolo",
    "Seedot",
    "Nuzleaf",
    "Shiftry",
    "Taillow",
    "Swellow",
    "Wingull",
    "Pelipper",
    "Ralts",
    "Kirlia",
    "Gardevoir",
    "Surskit",
    "Masquerain",
    "Shroomish",
    "Breloom",
    "Slakoth",
    "Vigoroth",
    "Slaking",
    "Nincada",
    "Ninjask",
    "Shedinja",
    "Whismur",
    "Loudred",
    "Exploud",
    "Makuhita",
    "Hariyama",
    "Azurill",
    "Nosepass",
    "Skitty",
    "Delcatty",
    "Sableye",
    "Mawile",
    "Aron",
    "Lairon",
    "Aggron",
    "Meditite",
    "Medicham",
    "Electrike",
    "Manectric",
    "Plusle",
    "Minun",
    "Volbeat",
    "Illumise",
    "Roselia",
    "Gulpin",
    "Swalot",
    "Carvanha",
    "Sharpedo",
    "Wailmer",
    "Wailord",
    "Numel",
    "Camerupt",
    "Torkoal",
    "Spoink",
    "Grumpig",
    "Spinda",
    "Trapinch",
    "Vibrava",
    "Flygon",
    "Cacnea",
    "Cacturne",
    "Swablu",
    "Altaria",
    "Zangoose",
    "Seviper",
    "Lunatone",
    "Solrock",
    "Barboach",
    "Whiscash",
    "Corphish",
    "Crawdaunt",
    "Baltoy",
    "Claydol",
    "Lileep",
    "Cradily",
    "Anorith",
    "Armaldo",
    "Feebas",
    "Milotic",
    "Castform",
    "Kecleon",
    "Shuppet",
    "Banette",
    "Duskull",
    "Dusclops",
    "Tropius",
    "Chimecho",
    "Absol",
    "Wynaut",
    "Snorunt",
    "Glalie",
    "Spheal",
    "Sealeo",
    "Walrein",
    "Clamperl",
    "Huntail",
    "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon",
    "Shelgon",
    "Salamence",
    "Beldum",
    "Metang",
    "Metagross",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Latios",
    "Kyogre",
    "Groudon",
    "Rayquaza",
    "Jirachi",
    "Deoxys",
  ],
  carros: [
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Bugatti",
    "Buick",
    "BYD",
    "Cadillac",
    "Caoa Chery",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Dacia",
    "Daihatsu",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "GMC",
    "GWM",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Iveco",
    "Jaguar",
    "Jeep",
    "Kia",
    "Koenigsegg",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lifan",
    "Lincoln",
    "Lotus",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Opel",
    "Pagani",
    "Peugeot",
    "Plymouth",
    "Pontiac",
    "Porsche",
    "Ram",
    "Renault",
    "Rolls-Royce",
    "Saab",
    "Saturn",
    "Scania",
    "Seat",
    "Shelby",
    "Skoda",
    "Smart",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Troller",
    "Volkswagen",
    "Volvo",
  ],
  series: [
    "Breaking Bad",
    "Game of Thrones",
    "Stranger Things",
    "Friends",
    "The Office",
    "Grey's Anatomy",
    "The Walking Dead",
    "The Crown",
    "Succession",
    "The Bear",
    "Narcos",
    "Peaky Blinders",
    "Black Mirror",
    "Dark",
    "La Casa de Papel",
    "The Boys",
    "The Last of Us",
    "Mandallorian",
    "Wandinha",
    "The Witcher",
    "Better Call Saul",
    "Dr. House",
    "Sherlock",
    "Lost",
    "Prison Break",
    "Suits",
    "Lucifer",
    "The Big Bang Theory",
    "How I Met Your Mother",
    "Modern Family",
    "Brooklyn Nine-Nine",
    "Ted Lasso",
    "Cobra Kai",
    "Vikings",
    "The Flash",
    "Arrow",
    "Smallville",
    "Supernatural",
    "The Vampire Diaries",
    "Gossip Girl",
    "One Piece",
    "Naruto",
    "Dragon Ball Z",
    "Attack on Titan",
    "Death Note",
    "Fullmetal Alchemist",
    "Demon Slayer",
    "Jujutsu Kaisen",
    "Hunter x Hunter",
    "My Hero Academia",
    "One Punch Man",
    "Bleach",
    "Sword Art Online",
    "Evangelion",
    "Cowboy Bebop",
    "Sailor Moon",
    "Pokémon",
    "Digimon",
    "Yu-Gi-Oh",
    "Saint Seiya",
    "Sopranos",
    "The Wire",
    "Mad Men",
    "The West Wing",
    "Succession",
    "Seinfeld",
    "Twin Peaks",
    "Fargo",
    "True Detective",
    "Chernobyl",
  ],
  games: [
    "Minecraft",
    "Roblox",
    "Fortnite",
    "League of Legends",
    "Grand Theft Auto V",
    "The Witcher 3",
    "Cyberpunk 2077",
    "God of War",
    "Elden Ring",
    "Skyrim",
    "Super Mario Odyssey",
    "The Legend of Zelda",
    "Red Dead Redemption 2",
    "The Last of Us",
    "Resident Evil",
    "Silent Hill",
    "Call of Duty",
    "Counter-Strike",
    "Valorant",
    "Overwatch",
    "Dota 2",
    "World of Warcraft",
    "StarCraft",
    "Diablo",
    "Fallout",
    "Mass Effect",
    "BioShock",
    "Halo",
    "Gears of War",
    "Uncharted",
    "Final Fantasy",
    "Kingdom Hearts",
    "Dark Souls",
    "Bloodborne",
    "Sekiro",
    "Hollow Knight",
    "Cuphead",
    "Stardew Valley",
    "Terraria",
    "Among Us",
    "Street Fighter",
    "Mortal Kombat",
    "Tekken",
    "Super Smash Bros",
    "Mario Kart",
    "Sonic the Hedgehog",
    "Crash Bandicoot",
    "Spyro the Dragon",
    "Tomb Raider",
    "Metal Gear Solid",
    "FIFA",
    "Pro Evolution Soccer",
    "NBA 2K",
    "Need for Speed",
    "Gran Turismo",
    "Pac-Man",
    "Tetris",
    "Donkey Kong",
    "Space Invaders",
    "Doom",
  ],
  personagens: [
    "Homem de Ferro",
    "Capitão América",
    "Thor",
    "Hulk",
    "Viúva Negra",
    "Homem-Aranha",
    "Batman",
    "Superman",
    "Mulher-Maravilha",
    "Coringa",
    "Mickey Mouse",
    "Donald Duck",
    "Pernalonga",
    "Tom e Jerry",
    "Scooby-Doo",
    "Bob Esponja",
    "Homer Simpson",
    "Bart Simpson",
    "Rick Sanchez",
    "Morty Smith",
    "Harry Potter",
    "Hermione Granger",
    "Ron Weasley",
    "Lord Voldemort",
    "Albus Dumbledore",
    "Luke Skywalker",
    "Darth Vader",
    "Princesa Leia",
    "Han Solo",
    "Yoda",
    "Sherlock Holmes",
    "James Bond",
    "Indiana Jones",
    "Lara Croft",
    "Mario",
    "Sonic",
    "Pikachu",
    "Naruto Uzumaki",
    "Goku",
    "Monkey D. Luffy",
    "Frodo Bolseiro",
    "Gandalf",
    "Aragorn",
    "Legolas",
    "Gollum",
    "Katniss Everdeen",
    "Edward Cullen",
    "Bella Swan",
    "Jon Snow",
    "Daenerys Targaryen",
    "Walter White",
    "Jesse Pinkman",
    "Tony Soprano",
    "Michael Scott",
    "Dwight Schrute",
    "Eleven",
    "Master Chief",
    "Kratos",
    "Joel Miller",
    "Ellie",
    "Aquaman",
    "Flash",
    "Lanterna Verde",
    "Cyborg",
    "Shazam",
    "Robin",
    "Asa Noturna",
    "Batgirl",
    "Arqueiro Verde",
    "Canário Negro",
    "Pantera Negra",
    "Doutor Estranho",
    "Feiticeira Escarlate",
    "Visão",
    "Homem-Formiga",
    "Vespa",
    "Senhor das Estrelas",
    "Gamora",
    "Groot",
    "Rocket Raccoon",
    "Magneto",
    "Professor X",
    "Wolverine",
    "Ciclope",
    "Tempestade",
    "Jean Grey",
    "Fera",
    "Vampira",
    "Gambit",
    "Deadpool",
    "Pateta",
    "Pluto",
    "Margarida",
    "Tio Patinhas",
    "Huguinho",
    "Zezinho",
    "Luisinho",
    "Popeye",
    "Olívia Palito",
    "Brutus",
    "Woody",
    "Buzz Lightyear",
    "Rex",
    "Slinky",
    "Relâmpago McQueen",
    "Mate",
    "Mike Wazowski",
    "James P. Sullivan",
    "Mr. Incrível",
    "Mulher Elástica",
    "Winnie the Pooh",
    "Tigrão",
    "Leitão",
    "Ió",
    "Barbie",
    "Ken",
    "He-Man",
    "She-Ra",
    "Esqueleto",
    "Lion-O",
    "Severus Snape",
    "Sirius Black",
    "Dobby",
    "Hagrid",
    "Draco Malfoy",
    "Chewbacca",
    "C-3PO",
    "R2-D2",
    "Bobba Fett",
    "Kylo Ren",
    "Bilbo Bolseiro",
    "Arwen",
    "Gimli",
    "Boromir",
    "Eowyn",
    "Jack Sparrow",
    "Will Turner",
    "Elizabeth Swann",
    "Davy Jones",
    "Barbossa",
    "Link",
    "Zelda",
    "Ganondorf",
    "Donkey Kong",
    "Yoshi",
    "Luigi",
    "Princess Peach",
    "Bowser",
    "Kirby",
    "Mega Man",
    "Luffy",
    "Zoro",
    "Nami",
    "Sanji",
    "Chopper",
    "Nezuko Kamado",
    "Tanjiro Kamado",
    "Satoru Gojo",
    "Yuji Itadori",
    "Eren Yeager",
  ],
};

// Generate 'Tudo Misturado' theme from all alphabetical themes
const allMixed = [];
Object.keys(THEMES).forEach((key) => {
  if (key !== "pokemons" && key !== "numeros") {
    allMixed.push(...THEMES[key]);
  }
});
THEMES.misturado = [...new Set(allMixed)];

// Sort all lists alphabetically, case-insensitive, handling accents
Object.keys(THEMES).forEach((key) => {
  if (key !== "pokemons") {
    THEMES[key].sort((a, b) =>
      a.localeCompare(b, "pt-BR", { sensitivity: "base" }),
    );
  }
});
